name: Build HMAPlusPlus KPM

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Download ARM Toolchain
      run: |
        wget -q https://developer.arm.com/-/media/Files/downloads/gnu/14.2.rel1/binrel/arm-gnu-toolchain-14.2.rel1-x86_64-aarch64-none-elf.tar.xz
        tar -xf arm-gnu-toolchain-14.2.rel1-x86_64-aarch64-none-elf.tar.xz
        echo "TOOLCHAIN_PATH=$(pwd)/arm-gnu-toolchain-14.2.rel1-x86_64-aarch64-none-elf/bin" >> $GITHUB_ENV
      
    - name: Clone KernelPatch Framework
      run: |
        git clone https://github.com/bmax121/KernelPatch.git KernelPatch
      
    - name: Build KPM Module
      run: |
        export TARGET_COMPILE=$TOOLCHAIN_PATH/aarch64-none-elf-
        export KP_DIR=$(pwd)/KernelPatch
        make
      
    - name: Upload KPM artifact
      uses: actions/upload-artifact@v3
      with:
        name: HMAPlusPlus-module
        path: '*.kpm'
        retention-days: 7
        
    - name: Show build info
      run: |
        echo "Build completed!"
        ls -la *.kpm
